"""The dirty-tree trap, and the guarantee it must not cost.

`tools/governed_run.py` `strict_code_identity()` refuses to name a governing commit
for a checkout that is not byte-clean. That refusal exists so a measurement can never
be attributed to code that is not committed, and it is kept exactly as strict here.

The defect it caused was elsewhere: `.gitignore` un-ignores `docs/audits/evidence/**`
so the LaTeX `*.log`/`*.out` rules cannot swallow a retained reproduction output. That
negation also un-ignored the interpreter's own cache, so importing a retained
reproducer wrote an untracked `docs/audits/evidence/<dir>/__pycache__/`, the tree went
dirty, and fourteen tests went red with no source change at all.

The first test fails if a generated bytecode directory under evidence can once again
dirty the tree. The second proves the strictness survived: a genuinely uncommitted
source change is still refused.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
GITIGNORE = ROOT / ".gitignore"

#: Everything a Python toolchain may drop beside a retained reproducer. None of it is
#: evidence, and none of it may reach `git status`.
GENERATED_UNDER_EVIDENCE = (
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/__pycache__/reproduce.cpython-312.pyc",
    "docs/audits/evidence/DEEP/NESTED/CASE/__pycache__/probe.cpython-311.pyc",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/stale.pyc",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/stale.pyo",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/.pytest_cache/CACHEDIR.TAG",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/.mypy_cache/missing_stubs",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/.ruff_cache/content",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/.ipynb_checkpoints/probe-checkpoint.ipynb",
)

#: Real evidence, and real uncommitted source. Every one of these MUST still dirty the
#: tree -- re-ignoring the caches above may not buy silence for any of them.
SOURCE_UNDER_EVIDENCE = (
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/new_probe.py",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/PRE.log",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/POST.out",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/measurements.json",
    "docs/audits/evidence/RP40_REVIEW_2026_09_19/cells.csv",
)


def _load():
    name = "governed_run_identity_test_subject"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / "governed_run.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


GR = _load()


def _git(repo: Path, *args: str) -> str:
    done = subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True, check=True)
    return done.stdout.strip()


def _write(repo: Path, relative: str, body: str = "generated\n") -> Path:
    path = repo / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


@pytest.fixture
def checkout(tmp_path: Path) -> Path:
    """A throwaway repository carrying THIS checkout's real `.gitignore`.

    The rules under test are the committed ones, not a paraphrase of them.
    """
    repo = tmp_path / "checkout"
    repo.mkdir()
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "satoshi@example.invalid")
    _git(repo, "config", "user.name", "Satoshi")
    (repo / ".gitignore").write_text(GITIGNORE.read_text(encoding="utf-8"), encoding="utf-8")
    _write(repo, "tools/governed_run.py", "# a tracked source file\n")
    _write(repo, "docs/audits/evidence/RP40_REVIEW_2026_09_19/reproduce.py", "print('retained')\n")
    _write(repo, "docs/audits/evidence/RP40_REVIEW_2026_09_19/PRE.log", "retained output\n")
    _git(repo, "add", ".gitignore", "tools/governed_run.py",
         "docs/audits/evidence/RP40_REVIEW_2026_09_19/reproduce.py",
         "docs/audits/evidence/RP40_REVIEW_2026_09_19/PRE.log")
    _git(repo, "commit", "-qm", "seed")
    assert _git(repo, "status", "--porcelain", "--untracked-files=all") == ""
    return repo


def test_a_generated_bytecode_directory_under_evidence_cannot_dirty_the_tree(checkout: Path):
    """The trap itself. Red here means a reproducer import can again turn the suite red."""
    head = GR.strict_code_identity(checkout)["value"]

    for relative in GENERATED_UNDER_EVIDENCE:
        _write(checkout, relative)

    dirty = _git(checkout, "status", "--porcelain", "--untracked-files=all")
    assert dirty == "", f"a generated artifact under evidence dirtied the checkout:\n{dirty}"
    assert GR.strict_code_identity(checkout) == {"kind": "git_commit", "value": head}


def test_the_committed_gitignore_ignores_those_paths_in_this_very_checkout():
    """Asserted against the live repository, not a copy: `git check-ignore` needs no file."""
    for relative in GENERATED_UNDER_EVIDENCE:
        done = subprocess.run(["git", "check-ignore", "-q", relative],
                              cwd=ROOT, capture_output=True, text=True)
        assert done.returncode == 0, f"{relative} is not ignored by the committed .gitignore"


def test_strict_code_identity_still_refuses_a_genuinely_uncommitted_source_change(checkout: Path):
    """The guarantee the repair may not weaken: uncommitted code never governs."""
    edited = checkout / "tools" / "governed_run.py"
    edited.write_text("# an uncommitted change to committed source\n", encoding="utf-8")
    with pytest.raises(GR.GovernedRunError) as refusal:
        GR.strict_code_identity(checkout)
    assert "clean checkout" in str(refusal.value)
    assert "tools/governed_run.py" in str(refusal.value), "the refusal must name what is uncommitted"

    _git(checkout, "checkout", "--", "tools/governed_run.py")
    GR.strict_code_identity(checkout)  # clean again


@pytest.mark.parametrize("relative", SOURCE_UNDER_EVIDENCE)
def test_uncommitted_evidence_of_its_own_still_refuses_a_governing_commit(checkout: Path, relative: str):
    """Re-ignoring the caches bought silence for caches only: a new reproducer, a PRE/POST
    output, a measurements file or a cell table under evidence still refuses to govern."""
    _write(checkout, relative, "not committed yet\n")
    with pytest.raises(GR.GovernedRunError) as refusal:
        GR.strict_code_identity(checkout)
    assert Path(relative).name in str(refusal.value)


def test_the_evidence_negation_is_still_in_force(checkout: Path):
    """The re-ignore rules must not have undone what line ~197 is for: a retained
    reproduction output under evidence is tracked deliberately, LaTeX rules notwithstanding."""
    assert "!docs/audits/evidence/**" in GITIGNORE.read_text(encoding="utf-8")
    _write(checkout, "docs/audits/evidence/NEW_REVIEW/POST.log", "reproduction output\n")
    dirty = _git(checkout, "status", "--porcelain", "--untracked-files=all")
    assert "docs/audits/evidence/NEW_REVIEW/POST.log" in dirty, \
        "a PRE/POST reproduction output under evidence was swallowed by the LaTeX *.log rule"
