"""PRE / P0 for the census-gate-OLAP order (predictor@aef4dc22):
reproduce Musashi's reviewed base from bytes, before any edit.

The order's P0 asks for five reproductions:

  1. the 8 focal tests of the reviewed commit;
  2. byte-for-byte regeneration of
     examples/research/crispdm_dataset_inventory.v1.json;
  3. regeneration of the 1,680-slice financial-data
     reconciliation with 0 physically missing;
  4. a THROWAWAY PostgreSQL database: load the inventory twice
     and prove 2 datasets, 2 aggregate series, 99 variables and
     1 receipt remain (idempotence);
  5. the historic ETL on a FRESH database with NO manual
     ALTER TABLE.

It also freezes the state of the ALREADY POPULATED cube
read-only (39 historical experiments, last performance load
2026-04-16, the six additive tables), and the frozen tips of the
six repositories the order names.

Nothing is written outside the throwaway databases and a
temporary directory. `predictor_olap` is never written; no
container is started, stopped or restarted; reset_olap.py is
never invoked."""
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
FIN = REPO.parent / "financial-data"
PY = sys.executable
RESEARCH = REPO / "examples/research"
REVIEWED_BASE = "aef4dc22e7a6039eb349b75caf5e9b5823607d5e"
INVENTORIED_AT = "2026-09-10T00:00:00Z"

# doc 02 (02_EVIDENCIA_IMPLEMENTACION_Y_OLAP.md) claims, consumed
# here as CLAIMS to reproduce, never as facts
CLAIMED = {
    "inventory_digest":
        "03be76a4c545eb60319053caf693560383b2c9f3119b2b2dcd70c1"
        "9b7018a2a0",
    "reconciliation_digest":
        "833e6afebaa85bf2bf3af73a843963ae85651412f152ca113c6473"
        "436a7c9947",
    "datasets": 2, "rows": 26541, "variables": 99,
    "slices_present": 1680, "slices_missing": 0,
    "declared_columns": 7860,
    "physical_bytes": 14436534039,
    "etl_facts": 72, "etl_skipped": 0,
    "historical_experiments": 39,
}

PGHOST = os.getenv("PGHOST", "127.0.0.1")
PGPORT = os.getenv("PGPORT", "5432")
PGUSER = os.getenv("PGUSER", "metabase")
PGPASSWORD = os.getenv("PGPASSWORD", "metabase_pass")
REAL_DB = "predictor_olap"
THROWAWAY_A = "predictor_olap_p0_repro_a"
THROWAWAY_B = "predictor_olap_p0_repro_b"


def sha_file(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def dsn(db):
    return (f"postgresql://{PGUSER}:{PGPASSWORD}@{PGHOST}:"
            f"{PGPORT}/{db}")


def admin_sql(stmt):
    from sqlalchemy import create_engine, text
    e = create_engine(dsn("postgres"), future=True,
                      isolation_level="AUTOCOMMIT")
    with e.connect() as c:
        c.execute(text(stmt))
    e.dispose()


def counts(db, tables):
    from sqlalchemy import create_engine, text
    e = create_engine(dsn(db), future=True)
    out = {}
    with e.connect() as c:
        for t in tables:
            out[t] = c.execute(
                text(f"select count(*) from {t}")).scalar()
    e.dispose()
    return out


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True,
                          cwd=str(REPO), **kw)


print("=== 0. frozen state ===")
head = run(["git", "rev-parse", "HEAD"]).stdout.strip()
print(f"predictor HEAD: {head[:12]}")
base_ok = run(["git", "merge-base", "--is-ancestor",
               REVIEWED_BASE, "HEAD"]).returncode == 0
print(f"reviewed base {REVIEWED_BASE[:12]} is an ancestor of "
      f"HEAD: {base_ok}")
assert base_ok
for name in ("financial-data", "preprocessor", "predictor",
             "agent-multi", "doin-domains", "doin-plugins"):
    d = REPO.parent / name
    if not (d / ".git").is_dir():
        print(f"  {name}: ABSENT")
        continue
    tip = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                         cwd=d, capture_output=True,
                         text=True).stdout.strip()
    br = subprocess.run(["git", "branch", "--show-current"],
                        cwd=d, capture_output=True,
                        text=True).stdout.strip()
    dirty = len(subprocess.run(
        ["git", "status", "--porcelain"], cwd=d,
        capture_output=True, text=True).stdout.splitlines())
    print(f"  {name:<15} {tip} on {br} (dirty files: {dirty})")

print("\n=== 1. the 8 focal tests of the reviewed base ===")
rc = run([PY, "-m", "pytest",
          "tests/unit_tests/test_crispdm_inventory.py",
          "tests/unit_tests/test_financial_data_reconciliation"
          ".py", "-q", "-p", "no:cacheprovider"])
tail = rc.stdout.strip().splitlines()[-1]
print(f"focal: {tail}")
assert rc.returncode == 0 and "8 passed" in tail

print("\n=== 2. inventory regenerated byte-for-byte ===")
tmp = Path(tempfile.mkdtemp(prefix="p0_repro_"))
try:
    inv_committed = RESEARCH / "crispdm_dataset_inventory.v1.json"
    inv_new = tmp / "inventory.json"
    rc = run([PY, "tools/build_crispdm_inventory.py",
              "--registry", str(RESEARCH /
                                "crispdm_dataset_registry.v1"
                                ".json"),
              "--root", f"predictor={REPO}",
              "--inventoried-at", INVENTORIED_AT,
              "--output", str(inv_new)])
    assert rc.returncode == 0, rc.stderr[-400:]
    a, b = sha_file(inv_committed), sha_file(inv_new)
    print(f"committed sha : {a}")
    print(f"regenerated   : {b}")
    print(f"BYTE-EQUAL    : {a == b}")
    assert a == b
    inv = json.loads(inv_committed.read_text())
    n_ds = len(inv["datasets"])
    n_var = sum(len(d["variables"]) for d in inv["datasets"])
    n_rows = sum(d["row_count"] for d in inv["datasets"])
    print(f"declared inside: {n_ds} datasets / {n_rows} rows / "
          f"{n_var} variables  (claim {CLAIMED['datasets']}/"
          f"{CLAIMED['rows']}/{CLAIMED['variables']})")
    assert (n_ds, n_rows, n_var) == (CLAIMED["datasets"],
                                     CLAIMED["rows"],
                                     CLAIMED["variables"])
    print(f"self digest re-derives: "
          f"{inv['inventory_sha256'] == CLAIMED['inventory_digest']}")
    assert inv["inventory_sha256"] == \
        CLAIMED["inventory_digest"]
    states = sorted({d["profile_status"]
                     for d in inv["datasets"]})
    print(f"dataset states: {states}")

    print("\n=== 3. financial-data reconciliation regenerated ===")
    rec_committed = (RESEARCH /
                     "financial_data_manifest_reconciliation.v1"
                     ".json")
    rec_new = tmp / "reconciliation.json"
    rc = run([PY, "tools/reconcile_financial_data_manifest.py",
              "--financial-data-root", str(FIN),
              "--inventoried-at", INVENTORIED_AT,
              "--output", str(rec_new)])
    assert rc.returncode == 0, rc.stderr[-400:]
    a, b = sha_file(rec_committed), sha_file(rec_new)
    print(f"committed sha : {a}")
    print(f"regenerated   : {b}")
    print(f"BYTE-EQUAL    : {a == b}")
    assert a == b
    rec = json.loads(rec_committed.read_text())
    s = rec["summary"]
    print(f"present {s['physical_present_count']} / missing "
          f"{s['physical_missing_count']} / declared columns "
          f"{s['declared_variable_count']} / bytes "
          f"{s['physical_size_bytes']}")
    assert s["physical_present_count"] == \
        CLAIMED["slices_present"]
    assert s["physical_missing_count"] == \
        CLAIMED["slices_missing"]
    assert s["declared_variable_count"] == \
        CLAIMED["declared_columns"]
    assert s["physical_size_bytes"] == CLAIMED["physical_bytes"]
    assert rec["reconciliation_sha256"] == \
        CLAIMED["reconciliation_digest"]
    print("self digest re-derives: True")

    print("\n=== 4. throwaway database: double load is "
          "idempotent ===")
    env = {**os.environ, "PGHOST": PGHOST, "PGPORT": PGPORT,
           "PGUSER": PGUSER, "PGPASSWORD": PGPASSWORD}
    admin_sql(f'DROP DATABASE IF EXISTS "{THROWAWAY_A}"')
    admin_sql(f'CREATE DATABASE "{THROWAWAY_A}"')
    enva = {**env, "PGDATABASE": THROWAWAY_A}
    rc = run([PY, "olap/init_db.py"], env=enva)
    assert rc.returncode == 0, rc.stderr[-500:]
    print("init_db on a fresh database: OK (no manual DDL)")
    for i in (1, 2):
        rc = run([PY, "tools/load_crispdm_inventory.py",
                  "--inventory", str(inv_committed)], env=enva)
        assert rc.returncode == 0, rc.stderr[-500:]
        print(f"  load #{i}: {rc.stdout.strip()}")
    TABLES = ("dim_dataset", "dim_series", "dim_variable",
              "fact_dataset_inventory", "fact_variable_profile",
              "fact_ingestion_receipt")
    got = counts(THROWAWAY_A, TABLES)
    print(f"after two loads: {json.dumps(got)}")
    assert got["dim_dataset"] == 2 and got["dim_series"] == 2
    assert got["dim_variable"] == 99
    assert got["fact_ingestion_receipt"] == 1
    assert got["fact_dataset_inventory"] == 2
    assert got["fact_variable_profile"] == 99

    print("\n=== 5. historic ETL on a FRESH database, no "
          "manual ALTER TABLE ===")
    admin_sql(f'DROP DATABASE IF EXISTS "{THROWAWAY_B}"')
    admin_sql(f'CREATE DATABASE "{THROWAWAY_B}"')
    envb = {**env, "PGDATABASE": THROWAWAY_B}
    rc = run([PY, "olap/init_db.py"], env=envb)
    assert rc.returncode == 0, rc.stderr[-500:]
    cfg = ("examples/config/phase_1/"
           "phase_1_ann_1575_1h_config.json")
    res = ("examples/results/phase_1/"
           "phase_1_ann_1575_1h_results.csv")
    pat = re.compile(r"^(Train|Validation|Test)\s+(.+?)\s+H(\d+)$")
    import csv as _csv
    n_rows = sum(1 for r in _csv.DictReader(
        open(REPO / res))
        if r.get("Metric") and pat.match(r["Metric"].strip()))
    print(f"fixture {Path(res).name}: {n_rows} parseable metric "
          f"rows (claim {CLAIMED['etl_facts']})")
    rc = run([PY, "olap/etl_migrate_v2.py",
              "--project-key", "predictor",
              "--phase-key", "phase_1",
              "--experiment-key", "ann_1575_1h",
              "--experiment-config", cfg,
              "--results-csv", res], env=envb)
    out = (rc.stdout + rc.stderr).strip().splitlines()
    print(f"etl exit: {rc.returncode}")
    for ln in out[-4:]:
        print(f"  {ln[:150]}")
    assert rc.returncode == 0, "ETL failed on a fresh database"
    fact_n = counts(THROWAWAY_B,
                    ("fact_performance",))["fact_performance"]
    print(f"fact_performance rows on the fresh database: "
          f"{fact_n} (claim {CLAIMED['etl_facts']} written, "
          f"{CLAIMED['etl_skipped']} skipped)")
    assert fact_n == CLAIMED["etl_facts"]

    print("\n=== 6. the POPULATED cube, read-only ===")
    from sqlalchemy import create_engine, text
    e = create_engine(dsn(REAL_DB), future=True)
    with e.connect() as c:
        exp = c.execute(
            text("select count(*) from dim_experiment")).scalar()
        last = c.execute(
            text("select max(loaded_at) from "
                 "fact_performance")).scalar()
        real = {t: c.execute(
            text(f"select count(*) from {t}")).scalar()
            for t in TABLES}
        perf = c.execute(
            text("select count(*) from fact_performance")
        ).scalar()
    e.dispose()
    print(f"historical experiments: {exp} (claim "
          f"{CLAIMED['historical_experiments']})")
    print(f"last performance load : {last}")
    print(f"fact_performance rows : {perf}")
    print(f"additive tables       : {json.dumps(real)}")
    assert exp == CLAIMED["historical_experiments"]
    assert real["dim_dataset"] == 2
    assert real["dim_variable"] == 99
    assert real["fact_ingestion_receipt"] == 1
    print("the populated cube received ZERO writes from this "
          "reproduction")
finally:
    for db in (THROWAWAY_A, THROWAWAY_B):
        try:
            admin_sql(f'DROP DATABASE IF EXISTS "{db}"')
        except Exception as exc:      # noqa: BLE001
            print(f"  (throwaway {db} not dropped: "
                  f"{exc.__class__.__name__})")
    shutil.rmtree(tmp, ignore_errors=True)

print("\n=== 7. what does NOT exist yet (the order's work) ===")
absent = {
    "incremental financial-data census (P1)":
        list((FIN).glob("**/crispdm_census*.json"))
        if FIN.is_dir() else [],
    "three-bank common index (P2)":
        list(RESEARCH.glob("*bank_index*")),
    "PUBLICLY_ELIGIBLE manifest (P3)":
        list(RESEARCH.glob("*eligibility*"))
        + list(RESEARCH.glob("*eligible*")),
    "selection-boundary audit (P4)":
        list((REPO / "tests").glob("**/*selection_boundary*")),
    "sealed selection design (P5)":
        list(RESEARCH.glob("*selection_design*")),
    "campaign envelope schema (P6)":
        [p for p in (REPO / "olap").glob("*envelope*")],
}
for what, found in absent.items():
    print(f"  ABSENT: {what}"
          if not found else f"  PRESENT: {what} -> {found}")
    assert not found, (what, found)

print("\nPRE CONFIRMED: Musashi's reviewed base reproduces "
      "exactly — 8 focal tests pass, both artifacts regenerate "
      "BYTE-IDENTICAL with their self-digests, the throwaway "
      "double load is idempotent (2/2/99/1), the historic ETL "
      "succeeds on a fresh database with no manual ALTER TABLE, "
      "and the populated cube stands untouched at 39 "
      "experiments. None of the order's P1-P6 artifacts exist.")
