-- fs_phase23_0001: additive schema for feature-selection phases 2 and 3.
-- GENERATED from predictor_olap_store.fs_phase23_store.ddl(); do not edit by hand.
-- Every statement is CREATE ... IF NOT EXISTS. Nothing is dropped, altered or rewritten.
-- Identity: UNIQUE (run_id, row_key) AND UNIQUE over the typed identity columns;
-- row_identity_sha256 (PRIMARY KEY) digests those columns; row_sha256 digests the
-- submitted row (canonical JSON); payload holds that JSON; stored_at is never digested.

CREATE TABLE IF NOT EXISTS fs_phase23_run ( run_id TEXT PRIMARY KEY, run_sha256 TEXT NOT NULL UNIQUE, population_id TEXT NOT NULL, phase TEXT NOT NULL CHECK (phase IN ('PHASE_2', 'PHASE_3', 'PHASE_2_3')), registration TEXT NOT NULL CHECK (registration IN ('CONTRACT_BOUND', 'FIRST_SUBMISSION')), contract_sha256 TEXT, campaign_sha256 TEXT, code_sha256 TEXT, input_sha256 TEXT, expected_json TEXT NOT NULL, created_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS fs_phase23_load_receipt ( receipt_sha256 TEXT PRIMARY KEY, run_id TEXT NOT NULL, population_id TEXT NOT NULL, table_name TEXT NOT NULL, unit_id TEXT, row_count INTEGER NOT NULL, distinct_identities INTEGER NOT NULL, inserted INTEGER NOT NULL, duplicates_ignored INTEGER NOT NULL, rows_sha256 TEXT NOT NULL, host_role TEXT, shard_id TEXT, submitted_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS feature_pair_metrics ( row_identity_sha256 TEXT PRIMARY KEY, row_sha256 TEXT NOT NULL, row_key TEXT NOT NULL, unit_id TEXT, run_id TEXT NOT NULL, population_id TEXT NOT NULL, feature_left TEXT NOT NULL, feature_right TEXT NOT NULL, fold TEXT NOT NULL, metric TEXT NOT NULL, lag INTEGER NOT NULL, method TEXT NOT NULL, params_sha256 TEXT NOT NULL, code_sha256 TEXT NOT NULL, metric_value DOUBLE, shared_support BIGINT, state TEXT, host_role TEXT, shard_id TEXT, payload TEXT NOT NULL, stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (feature_left < feature_right), CHECK (lag >= 0), CHECK (state IS NULL OR state IN ('MEASURED', 'INSUFFICIENT_SUPPORT', 'NOT_APPLICABLE', 'FAILED')), UNIQUE (run_id, row_key), UNIQUE (run_id, population_id, feature_left, feature_right, fold, metric, lag, method, params_sha256, code_sha256));

CREATE TABLE IF NOT EXISTS feature_pair_stability ( row_identity_sha256 TEXT PRIMARY KEY, row_sha256 TEXT NOT NULL, row_key TEXT NOT NULL, unit_id TEXT, run_id TEXT NOT NULL, population_id TEXT NOT NULL, feature_left TEXT NOT NULL, feature_right TEXT NOT NULL, metric TEXT NOT NULL, lag INTEGER NOT NULL, method TEXT NOT NULL, params_sha256 TEXT NOT NULL, code_sha256 TEXT NOT NULL, metric_value DOUBLE, valid_folds INTEGER, state TEXT, host_role TEXT, shard_id TEXT, payload TEXT NOT NULL, stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (feature_left < feature_right), CHECK (lag >= 0), CHECK (state IS NULL OR state IN ('MEASURED', 'INSUFFICIENT_SUPPORT', 'NOT_APPLICABLE', 'FAILED')), UNIQUE (run_id, row_key), UNIQUE (run_id, population_id, feature_left, feature_right, metric, lag, method, params_sha256, code_sha256));

CREATE TABLE IF NOT EXISTS feature_pair_gate ( row_identity_sha256 TEXT PRIMARY KEY, row_sha256 TEXT NOT NULL, row_key TEXT NOT NULL, unit_id TEXT, run_id TEXT NOT NULL, population_id TEXT NOT NULL, feature_left TEXT NOT NULL, feature_right TEXT NOT NULL, fold TEXT NOT NULL, method TEXT NOT NULL, params_sha256 TEXT NOT NULL, code_sha256 TEXT NOT NULL, gate_state TEXT, shared_support BIGINT, host_role TEXT, shard_id TEXT, payload TEXT NOT NULL, stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (feature_left < feature_right), UNIQUE (run_id, row_key), UNIQUE (run_id, population_id, feature_left, feature_right, fold, method, params_sha256, code_sha256));

CREATE TABLE IF NOT EXISTS feature_alias_groups ( row_identity_sha256 TEXT PRIMARY KEY, row_sha256 TEXT NOT NULL, row_key TEXT NOT NULL, unit_id TEXT, run_id TEXT NOT NULL, population_id TEXT NOT NULL, group_id TEXT NOT NULL, representative TEXT, disposition TEXT, members_json TEXT, host_role TEXT, shard_id TEXT, payload TEXT NOT NULL, stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (run_id, row_key), UNIQUE (run_id, population_id, group_id));

CREATE TABLE IF NOT EXISTS feature_redundancy_clusters ( row_identity_sha256 TEXT PRIMARY KEY, row_sha256 TEXT NOT NULL, row_key TEXT NOT NULL, unit_id TEXT, run_id TEXT NOT NULL, population_id TEXT NOT NULL, cluster_id TEXT NOT NULL, representative TEXT, size INTEGER, members_json TEXT, host_role TEXT, shard_id TEXT, payload TEXT NOT NULL, stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (run_id, row_key), UNIQUE (run_id, population_id, cluster_id));

CREATE TABLE IF NOT EXISTS feature_filter_rankings ( row_identity_sha256 TEXT PRIMARY KEY, row_sha256 TEXT NOT NULL, row_key TEXT NOT NULL, unit_id TEXT, run_id TEXT NOT NULL, population_id TEXT NOT NULL, target_id TEXT NOT NULL, horizon INTEGER NOT NULL, method TEXT NOT NULL, params_sha256 TEXT NOT NULL, feature_id TEXT NOT NULL, rank INTEGER, score DOUBLE, causal_label TEXT, host_role TEXT, shard_id TEXT, payload TEXT NOT NULL, stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (run_id, row_key), UNIQUE (run_id, population_id, target_id, horizon, method, params_sha256, feature_id));

CREATE TABLE IF NOT EXISTS feature_filter_subsets ( row_identity_sha256 TEXT PRIMARY KEY, row_sha256 TEXT NOT NULL, row_key TEXT NOT NULL, unit_id TEXT, run_id TEXT NOT NULL, population_id TEXT NOT NULL, target_id TEXT NOT NULL, horizon INTEGER NOT NULL, method TEXT NOT NULL, params_sha256 TEXT NOT NULL, k INTEGER NOT NULL, subset_sha256 TEXT, label TEXT, members_json TEXT, is_final_selection BOOLEAN, host_role TEXT, shard_id TEXT, payload TEXT NOT NULL, stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (run_id, row_key), UNIQUE (run_id, population_id, target_id, horizon, method, params_sha256, k));

CREATE OR REPLACE VIEW fs_phase23_coverage AS SELECT r.run_id, r.population_id, r.phase, r.registration, (SELECT count(*) FROM feature_pair_metrics x WHERE x.run_id = r.run_id) AS feature_pair_metrics_rows, (SELECT count(*) FROM feature_pair_stability x WHERE x.run_id = r.run_id) AS feature_pair_stability_rows, (SELECT count(*) FROM feature_pair_gate x WHERE x.run_id = r.run_id) AS feature_pair_gate_rows, (SELECT count(*) FROM feature_alias_groups x WHERE x.run_id = r.run_id) AS feature_alias_groups_rows, (SELECT count(*) FROM feature_redundancy_clusters x WHERE x.run_id = r.run_id) AS feature_redundancy_clusters_rows, (SELECT count(*) FROM feature_filter_rankings x WHERE x.run_id = r.run_id) AS feature_filter_rankings_rows, (SELECT count(*) FROM feature_filter_subsets x WHERE x.run_id = r.run_id) AS feature_filter_subsets_rows, (SELECT count(*) FROM fs_phase23_load_receipt l WHERE l.run_id = r.run_id) AS receipts FROM fs_phase23_run r;
